/**
 * Cloudflare Worker environment bindings.
 *
 * These are auto-generated by `wrangler types` but we declare them here for
 * editor support and to be the single source of truth across the codebase.
 */
interface Env {
  // Static assets
  ASSETS: Fetcher;

  // D1 database (SQLite)
  DB: D1Database;

  // R2 object storage for documents
  DOCUMENTS: R2Bucket;

  // KV namespace for caching
  CACHE: KVNamespace;
}
